/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyStablecoin } from './MyStablecoin.js';
export * as factories from './factories/index.js';
export { MyStablecoin__factory } from './factories/MyStablecoin__factory.js';